
name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
      - uses: actions/checkout@v4

      - name: Run a one-line script
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: echo ${{ toJson(github) }}

